### ISSUE TITLE
Sample Repository return 400

### ISSUE THREAD

**Issue by haruharuharuby** [talkyjs/talkyjs-alexa-skill-template-helloworld#2]
Tried along with readme. Git Repository return 400 error.

`
-> % ask cli --version
2.11.1`

`[Warn]: CLI is about to download the skill template from unofficial template https://github.com//talkyjs/talkyjs-alexa-skill-template-helloworld.git. Please make sure you understand the source code to best protect yourself from malicious usage.
? Would you like to continue download the skill template?  Yes
? Please type in your skill name:  talkyjs-alexa-skill-template-helloworld
? Please type in your folder name for the skill project (alphanumeric):  talkyjs-alexa-skill-template-helloworld
fatal: unable to access 'https://github.com//talkyjs/talkyjs-alexa-skill-template-helloworld.git/': The requested URL returned error: 400
[Error]: CliError: Error: Command failed: git clone --branch ask-cli-x https://github.com//talkyjs/talkyjs-alexa-skill-template-helloworld.git "/Users/tomoharuitoh/hugtech/alexa-summer-memory/talkyjs-alexa-skill-template-helloworld"  --quiet`

**Comment by hideokamoto** [comment]
I've fixed the readme.md.
